development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username: user
  database: paper_prod

staging_squallstar:
   adapter: mysql2
   encoding: utf8
   collation: utf8_unicode_ci
   database: <%= ENV['DATABASE_NAME'] %>
   pool: 10
   username: paperboard
   password: <%= ENV['DATABASE_PASSWORD'] %>
   socket: /var/run/mysqld/mysqld.sock
   reconnect: true

production_squallstar:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 10
  username: paperboard
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true