development:
  adapter: postgresql
  host: localhost
  database: paper_dev
  encoding: unicode

test:
  adapter: postgresql
  host: localhost
  database: paper_test
  encoding: unicode

production:
  adapter: postgresql
  host: localhost
  username: user
  database: paper_prod